Repository apache/maven-javadoc-plugin, pull requests merged in 2025-08, with the labels that each got.

#1226 Maven Archiver 3.6.4
  pom.xml
Labels: dependencies

#1238 protect 3.8.x branch
  .asf.yaml
Labels: bug

#1240 Remove Javadoc 1.4+ / -1.1 switch related warning
  src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Labels: bug

#1260 Delete flaky test
  src/it/projects/MJAVADOC-611_dependencyLinks/invoker.properties
  src/it/projects/MJAVADOC-611_dependencyLinks/pom.xml
  src/it/projects/MJAVADOC-611_dependencyLinks/src/main/java/foo/Bar.java
  src/it/projects/MJAVADOC-611_dependencyLinks/verify.groovy
Labels: skip-changelog

#1259 detectOfflineLinks is now false per default for all *jar* mojo issue #1258
  src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
  src/main/java/org/apache/maven/plugins/javadoc/JavadocJarMojo.java
Labels: breaking
